version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: springuru
      # Postgres liest das Passwort direkt aus der Secret-Datei
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-net
    deploy:
      placement:
        constraints:
          - node.role == manager

  app:
    image: megmus/springbootdocker:1.0.4
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/springuru
      - SPRING_DATASOURCE_USERNAME=admin
      # Der offizielle Spring-Weg für Docker Secrets
      - SPRING_DATASOURCE_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    networks:
      - backend-net
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

networks:
  backend-net:
    driver: overlay

secrets:
  postgres_password:
    external: true

volumes:
  db_data: